### ISSUE TITLE
Clicking "toggle all" changes value of required apps

### ISSUE THREAD

**Issue by esavage-sandstorm** [KIProtect/klaro#141] opened 2019-12-11 20:52 UTC
**Steps to reproduce**

Have multiple applications configured within the config, with at least one that is true by default and required.
Open the detailed settings of the Klaro modal.
With all apps true, click the "toggle all"

**Current behavior**

All consents are set to false, including the required one.
All toggles but the required one switch to their inactive state.

On next page load, the klaro cookie reflects the required app is false, even though the toggle did not change.

**Expected behavior**
The required app should remain unaffected by the "toggle all"; it should remain its default value, and the toggle should match the value of the app consent.

**Comment by futureweb** [comment] 2019-12-12 10:13
@esavage-sandstorm - get latest JS Version - this behaviour is already fixed ... had the same prob ... ;-)

https://unpkg.com/klaro
https://www.npmjs.com/package/klaro

**Comment by jaller94** [comment] 2019-12-12 12:32
@futureweb Thanks for pointing it out.

Duplicate of #92.
Fixed in #112.
Released in [v0.2.11](https://github.com/KIProtect/klaro/releases/tag/v0.2.11) (not the latest release⚠).

**Closed by jaller94** 2019-12-12 12:32 UTC
