### ISSUE TITLE
Font size inconsistent

### ISSUE THREAD

**Issue by apptum** [kiprotect/klaro#232] opened 2020-06-30 09:04 UTC
**Current behavior**
the font-sizes of buttons currently depends on the amount of text-content, f.e.:
![image](https://user-images.githubusercontent.com/7722596/86106504-ea8fc800-bac0-11ea-83da-7b2a050bcbfe.png)
(btw. I changed the order of the btns via css)
The green button saying "agree!" looks much less significant than the grey decline-all "notwendige".

A consistent font-size in buttons, mostly the accept, acceptAll, declineAll would not only improve designwise, but would help to nudge users to accept all (in my case)

**Comment by adewes** [comment] 2020-07-22 16:01
![image](https://user-images.githubusercontent.com/550026/88199535-46bfb500-cc45-11ea-90e8-140f129f86f8.png)

I can't reproduce this in the latest version, the font sizes seem to be identical. Are you sure there isn't a CSS rule added by your website that leaks into Klaro's scope?

**Comment by adewes** [comment] 2020-07-29 06:51
Closing this, please reopen if the problem should pop up again.

**Closed by adewes** 2020-07-29 06:51 UTC
