### ISSUE TITLE
No placeholder for external content at first pageload

### ISSUE THREAD

**Issue by rachedamer** [kiprotect/klaro#361] opened 2021-02-10 18:04 UTC
I just installed Klaro at https://www.senkrechtstarter.org/ and it seems to be working fine. Only issue is, once I disable Youtube, the consent manager just disappears and the Youtube area remains blank. Once I reload the page, I get the Klaro “Would you like to load external … (Yes/Always)” message – which I would really like to be there right away. Is there any config option I missed to display that message right away in case the user disagrees to loading Youtube?

**Comment by adewes** [comment] 2021-02-10 20:46
Hi @rachedamer! This issue will be addressed with the next Klaro release that'll come out this week.

**Comment by rachedamer** [comment] 2021-02-17 21:56
Thanks! 0.7.12 solved it.

**Comment by varavin** [comment] 2021-03-19 15:42
@rachedamer the Youtube areas at www.senkrechtstarter.org are still empty upon the first page load (until you click one of the buttons in consent manager popup in the bottom right of the screen). Do you think is that a supposed behaviour? I wonder why Klaro's placeholders don't appear by default, that looks more like a bug and I have the same behaviour in the version I downloaded today.

**Comment by adewes** [comment] 2021-03-19 15:46
Hey @varavin, I looked at your config and it seems you didn't enable the `contextualConsentOnly` option for the `youtube` service. Can you try adding `contextualConsentOnly: true` to that? Sorry if that's not 100 % clear from the documentation, Klaro won't put placeholder on elements unless you specify this option, as this would break in some other cases.

**Comment by garvinhicking** [comment] 2021-03-31 07:58
I sadly face the same problem. Instead of opening a new issue here are my details:

**Klaro Config**

```
var klaroConfig = {
    version: 1,
    elementID: 'klaro',
    styling: {
        theme: ['light', 'top', 'wide'],
    },
    noAutoLoad: false,
    htmlTexts: true,
    embedded: false,
    groupByPurpose: true,
    storageMethod: 'cookie',
    cookieName: 'klaro-cookie-consent',
    cookieExpiresAfterDays: 365,
    default: false,
    mustConsent: false,
    acceptAll: true,
    hideDeclineAll: false,
    hideLearnMore: false,
    noticeAsModal: false,
    lang: 'de',
    translations: {
        zz: {
            purposes: {
                externalService: 'Externe Medien'
            },
            externalService: {
                title: 'Einbindung externer Medien',
                description: 'BESCHREIBUNG[Einbindung externer Medien]',
            },
        }
    },
    services: [
        {
            name: 'youtube',
            purposes: ['externalService'],
            contextualConsentOnly: true,
            default: true,
            title: 'Google Youtube',
            description: 'YouTube Videos anzeigen & abspielen',
        }
    ],
};
```

**HTML Code of Page**
 
```
<iframe data-type="youtube" width="560" height="315" frameborder="0" allow="accelerometer; autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen data-name="youtube" data-src="https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ"></iframe>
```

**Steps to reproduce**

Using this config I would expect on first page load (i.e. no tracking cookies exist) that the page shows the placeholder for this youtube frame.

Indeed the HTML DOM does contain the placeholder (even though it only has one button, not the "Always allow" one), but it is rendered with inline style "display: none".

It does not matter if I set contextualConsentOnly to true or false.

Once I actually deny all cookies the placeholder is shown as intended.

I figure the expected behaviour would be to show the consent placeholders also on first pagecall, right? Funnily in the documentation example (https://heyklaro.com/docs/tutorials/contextual_consent) I see it working there as expected but for the life of me I cannot figure out the difference.

Sadly our current implementation is work-in-progress and I cannot disclose it here (but happily could do it privately).

Great work on klaro, I totally love it. I haven't used a tool in the past that was so easy to setup and integrate. Very well done.

**Comment by adewes** [comment] 2021-03-31 08:56
Hey @garvinhicking, please send me a URL to klaro@kiprotect.com, I can't debug this otherwise. The "Always Accept" button is not displayed before the user grants consent via the notice as we don't have a way to persist the contextual consent otherwise. Please note that we copy the style of the original element to the placeholder, so if you have a `display: none` inline style on your original element Klaro will apply that to the placeholder as well (we do this to honor `inline`, `inline-block` styles). That is one explanation for the behavior that I can think of.

**Comment by garvinhicking** [comment] 2021-03-31 09:54
Thank you, just contacted you. Many thanks for the insanely fast response, much appreciated.

(The iframe/parent itself is not styled via inline or CSS rules)

If we are able to resolve the issue I'll make sure to document it here for anyone reading this.

**Comment by adewes** [comment] 2021-03-31 10:15
Ok great, for reference I'm going to post the probable issue:

For the service in question the `default: true` option was set, which caused the placeholder to not be shown. We'll fix this behavior with the next release, this didn't show up in our tests since we never used the `default: true` for contextual consent (and as it's in principle incompatible with it). Will be addressed in the next minor release.

**Comment by adewes** [comment] 2021-04-11 08:53
This should be fixed with the release from last week, please let me know if that isn't the case.

**Closed by adewes** 2021-04-11 08:53 UTC
Labels: bug, enhancement
